### ISSUE TITLE
Permission denied error when writing to /.s3cfg in OSX?

### ISSUE THREAD

**Issue by peterkappus** [frioux/s3cmd.dkr#1]
Hi @frioux! Thanks for this awesome little s3cmd docker image. When I try to configure it in OSX, something funny happens where ~/.s3cfg becomes a directory (rather than a file) and I get a "permission denied" error when `s3cmd` tries to write to it at the end.

Any ideas? Also, FYI, I've noticed that the readme shows the param as "configure" but I had to make it "--configure". Session output below. I hope it helps to debug the first issue.

thanks!
PK

```
$ mkdir ~/.s3cfg

$ docker run -it --rm         \
>   --volume ~/.s3cfg:/.s3cfg \
>   --user $(id -u)           \
>   frew/s3cmd                \
>   -- configure

...(go through config steps)...


Save settings? [y/N] y

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please report the following lines to:
   s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Problem: OSError: [Errno 13] Permission denied: '/.s3cfg'
S3cmd:   1.1.0-beta3

Traceback (most recent call last):
  File "/usr/bin/s3cmd", line 1800, in <module>
    main()
  File "/usr/bin/s3cmd", line 1715, in main
    run_configure(options.config, args)
  File "/usr/bin/s3cmd", line 1316, in run_configure
    os.remove(config_file)
OSError: [Errno 13] Permission denied: '/.s3cfg'

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
    Please report the above lines to:
   s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by frioux** [comment]
Hah, it's because you did `mkdir ~/.s3cmd`,  Try changing the very beginning to `touch ~/.s3cmd`;  Let me know if that works and I'll fix my buggy docs.

**Comment by peterkappus** [comment]
Thanks for the quick reply! :) I've just tried using `touch ~/.s3cfg` (I think you meant .s3cfg and not .s3cmd) but alas I still get the following:
```
Save settings? [y/N] y
ERROR: Writing config file failed: /.s3cfg: Permission denied
```
At least I don't get an s3cmd traceback-style error as I did before...

**Comment by frioux** [comment]
ugh, volumes are all different now than when I made this. I suspect we'll need to mount a directory and pass a path or set an env var to where it is for s3cmd to find it, maybe I'll just accept the changes you suggested before :)

Let me try some stuff.
